name: Check the source code
on:
  pull_request:
    branches:
      - develop
jobs:
  test:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm ci
      - name: Prettier
        run: expo format:fix
      - name: Lint
        run: expo lint:fix
